<?php

namespace frontend\assets;

use yii\web\AssetBundle;

/**
 * Main frontend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    //public $basePath = '@webroot';
    //public $baseUrl = '@web';
    public $sourcePath = '@frontend/media';
    public $css = [

//        'css/animate.3.2.3.css', //*last
        'css/prefix2.css', //*last
        'css/style_all.min.css', //*last
    ];
    public $js = [
//        'js/bootstrap/bootstrap.4.1.0.min.js',
//        'js/bootstrap/popper.1.14.0.min.js',
        'js/owl.carousel.min.js',
        //'js/select2.full.js',

        //'js/scrollupbar.js',
//        'js/perfect-scrollbar.js',
//        'js/perfect-scrollbar.jquery.js',
//        'js/jquery.scrolly.js', //
        'js/bootstrap-submenu.js',
        //'//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js',
       // 'js/slick.min.js',

        //'/uploads/newin.js?v=2017-11-13-v3',
        'js/jquery.lazy.min.js',
        'js/all.js',
        'js/scripts.js',
        //'//code.jquery.com/jquery-2.2.4.min.js',
        //'//cdunjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js',
        //'//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js',
        //'js/scriptsnew.js?v=2017-12-08-v6',


        //'//widget.privy.com/assets/widget.js',

        //'js/frontend.js'
    ];
    public $depends = [
        'yii\web\JqueryAsset',
        //'frontend\assets\FoundationTableAsset',
        //'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'yii\web\YiiAsset',
    ];

    public function init()
    {
        if (!YII_DEBUG) {
            $this->css = [
                'css/style_all.min.css'
            ];
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}
