<?php

namespace frontend\modules\licenses\api;


use frontend\modules\licenses\models\LicensesExt;
use frontend\modules\licenses\models\LicensesTranslation;
use Yii;
use yii\data\ActiveDataProvider;
use frontend\models\Tag;
use frontend\widgets\Fancybox;
use yii\widgets\LinkPager;
use frontend\modules\licenses\models\Licenses as LicensesModel;
use yii\web\NotFoundHttpException;

/**
 * Page module API
 * @package frontend\modules\Licenses\api
 *
 * @property ActiveDataProvider $_adp
 * @method static LicensesObject get(mixed $id_slug) Get page object by id or slug
 * @method static array items(array $options = []) Get list of page as LicensesObject objects
 * @method static mixed last(int $limit = 1) Get last page
 * @method static mixed clear() Clear items
 * @method static void plugin() Applies FancyBox widget on photos called by box() function
 * @method static string pages() returns pagination html generated by yii\widgets\LinkPager widget.
 * @method static \stdClass pagination() returns yii\data\Pagination object.
 */
class Licenses extends \common\components\API
{
    private $_adp;
    private $_last;
    private $_items;
    private $_item = [];


    public function api_items($options = [])
    {
        $this->_items = [];

        $with[] = 'seo';
        if (Yii::$app->getModule('admin')->activeModules['page']->settings['enableTags']) {
            $with[] = 'tags';
        }
        $query = LicensesModel::find()
            //->select([LicensesModel::tableName().'.*', LicensesTranslation::tableName().'.*'])
            ->joinWith('translation')
            ->joinWith('child')
            ->with($with)
            ->andWhere([LicensesModel::tableName() . '.type_id' => LicensesModel::TYPE_ID])
            ->andWhere([LicensesTranslation::tableName() . '.public_status' => LicensesTranslation::STATUS_ON])
            ->status(LicensesModel::STATUS_ON);

        if (!empty($options['where'])) {
            $query->andFilterWhere($options['where']);
        }
        if (!empty($options['whereCountry'])){
            $query->andFilterWhere($options['whereCountry']);
        }

        if (!empty($options['tags'])) {
            $query
                ->innerJoinWith('tags', false)
                ->andWhere([Tag::tableName() . '.name' => (new LicensesModel)->filterTagValues($options['tags'])])
                ->addGroupBy('id');
        }

        if (!empty($options['list'])) {
            $query->orderBy(LicensesTranslation::tableName() . '.name');

        } elseif (!empty($options['orderBy'])) {
            if ($options['orderBy'] === 'title') {
                $query->orderBy(LicensesTranslation::tableName() . '.name');
            } else {
                $query->orderBy($options['orderBy']);
            }
        } else {
            $query->sortDate();
        }

        $this->_adp = new ActiveDataProvider([
            'query' => $query,
            'pagination' => !empty($options['pagination']) ? $options['pagination'] : []
        ]);

        /**
         * @var \frontend\modules\Licenses\models\Licenses $model
         */
        foreach ($this->_adp->models as $model) {
            $oneItem = new LicensesObject($model);
            $this->_items[] = $oneItem;
        }

        return $this->_items;
    }

    public function api_get($id_slug)
    {
        if (!isset($this->_item[$id_slug])) {
            $this->_item[$id_slug] = $this->findPage($id_slug);
        }
        if( !$this->_item[$id_slug]){
            throw new NotFoundHttpException('Page Houston, we have a problem.');
        }
        else return $this->_item[$id_slug];
    }

    public function api_last($limit = 1)
    {
        if ($limit === 1 && $this->_last) {
            return $this->_last;
        }

        $with = ['seo'];
        if (Yii::$app->getModule('admin')->activeModules['page']->settings['enableTags']) {
            $with[] = 'tags';
        }

        $result = [];
        foreach (LicensesModel::find()->with($with)->status(LicensesModel::STATUS_ON)->sortDate()->limit($limit)->all() as $item) {
            $result[] = new LicensesObject($item);
        }

        if ($limit > 1) {
            return $result;
        } else {
            $this->_last = count($result) ? $result[0] : null;
            return $this->_last;
        }
    }

    public function api_plugin($options = [])
    {
        Fancybox::widget([
            'selector' => '.easyii-box',
            'options' => $options
        ]);
    }

    public function api_pagination()
    {
        return $this->_adp ? $this->_adp->pagination : null;
    }

    public function api_pages()
    {
        $this->_adp->pagination->pageSizeParam = false;

        if ($this->_adp) {
            return LinkPager::widget(['pagination' => $this->_adp->pagination]);
        }
        return '';
    }

    private function findPage($id_slug)
    {
        $page = LicensesModel::find()
            ->joinWith('translation')
            ->joinWith('child')
            ->where(['or', LicensesModel::tableName() . '.id=:id_slug', LicensesModel::tableName() . '.slug=:id_slug'], [':id_slug' => $id_slug])
            ->andWhere([LicensesModel::tableName() . '.type_id' => LicensesModel::TYPE_ID])
            ->status(LicensesModel::STATUS_ON)
            ->one();

        if (!$page) {

            $errorMessage = 'Страница без перевода!!!: ' . $id_slug . '  .#36561';

            //if (!$this->mailApi($errorMessage)) {
            //header("HTTP/1.0 404 Not Found");
            //header("Location: " . Url::to(['/404/error/mailsend'], true));
            //exit;s
            //}

            $page = LicensesModel::find()
                //->joinWith('translation')
                ->where(['or', LicensesModel::tableName() . '.id=:id_slug', LicensesModel::tableName() . '.slug=:id_slug'], [':id_slug' => $id_slug])
                ->andWhere([LicensesModel::tableName().'.type_id'=>LicensesModel::TYPE_ID])
                ->status(LicensesModel::STATUS_ON)
                ->one();
        }

        if ($page) {
            $page->updateCounters(['views' => 1]);
            $page = new LicensesObject($page);

            return $page;
        } else {
            return false;
        }
    }

    private function notFound($id_slug)
    {
        $page = new LicensesModel([
            'slug' => $id_slug
        ]);
        return new LicensesObject($page);
    }

    public function api_clear()
    {
        $this->_adp = false;
        $this->_last = false;
        $this->_items = false;
        $this->_item = [];
    }
    public function api_getcountry($cat){
        $countryList = LicensesExt::find()
            -> select (['country'])
            ->distinct()
            -> where([LicensesExt::tableName().'.lic_type' => $cat])
            -> orderBy(['country' => SORT_ASC])
            ->all();
        return $countryList;
    }

}