<?php
namespace frontend\modules\seo\api;

use frontend\models\Option;
use Yii;
use yii\data\ActiveDataProvider;
use frontend\models\Tag;
use frontend\widgets\Fancybox;
use yii\db\Query;
use yii\widgets\LinkPager;

use frontend\modules\seo\models\Seo as SeoModel;

/**
 * Seo module API
 * @package frontend\modules\seo\api
 *
 * @method static SeoObject get(mixed $id_slug) Get seo object by id or slug
 * @method static array items(array $options = []) Get list of seo as SeoObject objects
 * @method static mixed last(int $limit = 1) Get last seo
 * @method static void plugin() Applies FancyBox widget on photos called by box() function
 * @method static string pages() returns pagination html generated by yii\widgets\LinkPager widget.
 * @method static \stdClass pagination() returns yii\data\Pagination object.
 */
class Seo extends \frontend\components\API
{
    private $_adp;
    private $_last;
    private $_items;
    private $_item = [];

    public function api_items($options = [])
    {
        //dsadas
        if (!$this->_items) {
            $this->_items = [];

/*            $subQuery = (new Query())
                ->select(['GROUP_CONCAT(op.title SEPARATOR ":: " )'])
                ->from('easyii_seo_properties_relations as opr')
                ->join('INNER JOIN', 'easyii_seo_properties as op', 'op.property_id = opr.property_id')
                ->where('opr.offer_id=easyii_seo.offer_id');*/

            $with = ['seo'];
            if (Yii::$app->getModule('admin')->activeModules['seo']->settings['enableTags']) {
                $with[] = 'tags';
            }
            $query = SeoModel::find()
                ->with($with)
                ->status(SeoModel::STATUS_ON);

            if (!empty($options['where'])) {
                $query->andFilterWhere($options['where']);
            }
            if (!empty($options['tags'])) {
                $query
                    ->innerJoinWith('tags', false)
                    ->andWhere([Tag::tableName() . '.name' => (new SeoModel)->filterTagValues($options['tags'])])
                    ->addGroupBy('offer_id');
            }
            if (!empty($options['type_id'])) {
                $query
                    ->andWhere([ 'type_id' => $options['type_id'] ]);
            }
            if (!empty($options['orderBy'])) {
                $query->orderBy($options['orderBy']);
            } else {
                $query->sortDate();
            }

            $this->_adp = new ActiveDataProvider([
                'query' => $query,
                'pagination' => !empty($options['pagination']) ? $options['pagination'] : []
            ]);

            foreach ($this->_adp->models as $model) {
                $item = new SeoObject($model);
                $item->properties = Option::find()
                    ->join(
                        'LEFT JOIN',
                        'easyii_options_assign as oa',
                        ' oa.`option_id` = `easyii_options`.`option_id`'
                    )
                    ->andWhere([
                        'item_id'  => (int)$model->offer_id,
                        'class'  => \frontend\modules\seo\models\Seo::className()
                    ])->all();

                $this->_items[] = $item;
            }
        }

        return $this->_items;
    }

    public function api_get($id_slug)
    {
        if (!isset($this->_item[$id_slug])) {
            $this->_item[$id_slug] = $this->findSeo($id_slug);
        }
        return $this->_item[$id_slug];
    }

    public function api_last($limit = 1)
    {
        if ($limit === 1 && $this->_last) {
            return $this->_last;
        }

        $with = ['seo'];
        if (Yii::$app->getModule('admin')->activeModules['seo']->settings['enableTags']) {
            $with[] = 'tags';
        }

        $result = [];
        foreach (SeoModel::find()->with($with)->status(SeoModel::STATUS_ON)->sortDate()->limit($limit)->all() as $item) {
            $result[] = new SeoObject($item);
        }

        if ($limit > 1) {
            return $result;
        } else {
            $this->_last = count($result) ? $result[0] : null;
            return $this->_last;
        }
    }

    public function api_plugin($options = [])
    {
        Fancybox::widget([
            'selector' => '.easyii-box',
            'options' => $options
        ]);
    }

    public function api_pagination()
    {
        return $this->_adp ? $this->_adp->pagination : null;
    }

    public function api_pages()
    {
        return $this->_adp ? LinkPager::widget(['pagination' => $this->_adp->pagination]) : '';
    }

    private function findSeo($id_slug)
    {
        $seo = SeoModel::find()
            ->where(['or', 'offer_id=:id_slug', 'slug=:id_slug'], [':id_slug' => $id_slug])
            ->status(SeoModel::STATUS_ON)
            ->one();
        if ($seo) {
            $seo->updateCounters(['views' => 1]);
            return new SeoObject($seo);
        } else {
            return null;
        }
    }
}